# This will appear before many messages from the plugin.
message-prefix: '&0[&5WWC&0]'

# Use a minecraft colour code here to pick the message colour
message-colour: 'e'

# The highlight colour (to complement the above colour)
highlight-colour: 'b'

# Errors will be this colour.
error-colour: 'c'

# Error highlights
error-highlight: '7'

item-models:
  wand: minecraft:breeze_rod
  spell: minecraft:flow_banner_pattern
  modifier: minecraft:globe_banner_pattern